disabled_rules: # rule identifiers to exclude from running
- trailing_whitespace
- cyclomatic_complexity
included: # paths to include during linting. `--path` is ignored if present.
- iOS
excluded: # paths to ignore during linting. Takes precedence over `included`.
- Pods
